name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v25
      - run: nix develop --command yarn install
      - run: nix develop --command yarn pack
      - run: nix develop --command yarn test
